// GENERATED by scripts/generate-service-index.ts — do not edit by hand.
// Run `npm run generate:service-index` after changing src/data/services.ts.

export interface IndexedCategory {
  id: string;
  ar: string;
  en: string;
}

export interface IndexedService {
  id: string;
  category: string;
  ar: string;
  en: string;
}

export const CATEGORY_INDEX: readonly IndexedCategory[] = [
  {"id":"residency","ar":"الإقامة والمعاملات","en":"Residency & Official Procedures"},
  {"id":"legal","ar":"الخدمات القانونية","en":"Legal Services"},
  {"id":"accounting","ar":"المحاسبة والضرائب","en":"Accounting & Tax"},
  {"id":"realestate","ar":"العقارات","en":"Real Estate"},
  {"id":"tourism","ar":"السياحة والتنقل","en":"Tourism & Transport"},
  {"id":"translation","ar":"الترجمة والمرافقة","en":"Translation & Companion"},
  {"id":"banking","ar":"الخدمات البنكية والتأمين","en":"Banking & Insurance"},
  {"id":"telecom","ar":"الاتصالات والمرافق","en":"Telecom & Utilities"},
  {"id":"health","ar":"الصحة","en":"Health"},
  {"id":"education","ar":"التعليم","en":"Education"},
  {"id":"business","ar":"تأسيس وتشغيل المشاريع","en":"Business Setup & Operations"},
  {"id":"daily","ar":"خدمات يومية وأخرى","en":"Daily & Other Services"},
];

export const SERVICE_INDEX: readonly IndexedService[] = [
  {"id":"res-tourist","category":"residency","ar":"إقامة سياحية (تقديم أول مرة)","en":"Tourist residence permit (first application)"},
  {"id":"res-property","category":"residency","ar":"إقامة عقارية","en":"Property-based residence permit"},
  {"id":"res-work","category":"residency","ar":"إقامة عمل","en":"Work residence permit"},
  {"id":"res-student","category":"residency","ar":"إقامة طالب","en":"Student residence permit"},
  {"id":"res-family","category":"residency","ar":"لمّ الشمل العائلي","en":"Family reunification"},
  {"id":"res-renew","category":"residency","ar":"تجديد الإقامة (كل الأنواع)","en":"Residence renewal (all types)"},
  {"id":"res-rejected","category":"residency","ar":"متابعة الطلبات المرفوضة والاعتراض","en":"Rejected applications & appeals"},
  {"id":"res-tax","category":"residency","ar":"استخراج الرقم الضريبي","en":"Tax number (Vergi No)"},
  {"id":"res-foreignid","category":"residency","ar":"استخراج الرقم الأجنبي (Yabancı Kimlik)","en":"Foreigner ID (Yabancı Kimlik)"},
  {"id":"res-appointment","category":"residency","ar":"حجز مواعيد دائرة الهجرة","en":"Immigration office appointments"},
  {"id":"tel-address","category":"residency","ar":"تسجيل العنوان (Adres Kaydı)","en":"Address registration (Adres Kaydı)"},
  {"id":"res-citizenship","category":"residency","ar":"خدمات الجنسية التركية","en":"Turkish citizenship services"},
  {"id":"res-eligibility","category":"residency","ar":"تدقيق مسار الإقامة والأهلية","en":"Residence path & eligibility check"},
  {"id":"visa-check","category":"residency","ar":"تدقيق التأشيرة ومتطلبات الدخول","en":"Visa & entry requirements check"},
  {"id":"legal-contracts","category":"legal","ar":"العقود التجارية والشراكات","en":"Commercial contracts & partnerships"},
  {"id":"legal-poa","category":"legal","ar":"التوكيلات الرسمية (Vekalet)","en":"Power of attorney (Vekalet)"},
  {"id":"legal-rent","category":"legal","ar":"قضايا الإيجار والعقارات","en":"Rental & property disputes"},
  {"id":"legal-labor","category":"legal","ar":"قضايا العمل","en":"Labor cases"},
  {"id":"legal-family","category":"legal","ar":"الزواج الرسمي والأحوال الشخصية (طلاق/حضانة)","en":"Marriage registration & family law (divorce/custody)"},
  {"id":"legal-liquidation","category":"legal","ar":"تصفية وإغلاق الشركات","en":"Company liquidation & closure"},
  {"id":"legal-consult","category":"legal","ar":"استشارة قانونية عامة","en":"General legal consultation"},
  {"id":"acc-monthly","category":"accounting","ar":"المحاسبة الشهرية للشركات","en":"Monthly company accounting"},
  {"id":"acc-kdv","category":"accounting","ar":"الإقرارات الضريبية (KDV)","en":"Tax declarations (KDV/VAT)"},
  {"id":"acc-payroll","category":"accounting","ar":"إدارة الرواتب والتأمينات (SGK)","en":"Payroll & social security (SGK)"},
  {"id":"acc-efatura","category":"accounting","ar":"الفواتير الإلكترونية (e-Fatura)","en":"E-invoicing (e-Fatura)"},
  {"id":"acc-consult","category":"accounting","ar":"استشارات ضريبية","en":"Tax consulting"},
  {"id":"re-rent","category":"realestate","ar":"إيجار شقق مفروشة وغير مفروشة","en":"Furnished & unfurnished rentals"},
  {"id":"re-buy","category":"realestate","ar":"بيع وشراء العقارات","en":"Buying & selling property"},
  {"id":"re-citizenship","category":"realestate","ar":"عقارات ضمن حد الاستثمار للجنسية","en":"Citizenship-threshold property"},
  {"id":"re-valuation","category":"realestate","ar":"التقييم العقاري (Ekspertiz)","en":"Property valuation (Ekspertiz)"},
  {"id":"re-management","category":"realestate","ar":"إدارة الأملاك للمستثمرين","en":"Property management for investors"},
  {"id":"re-contracts","category":"realestate","ar":"عقود الإيجار الموثّقة","en":"Notarized rental contracts"},
  {"id":"tour-airport","category":"tourism","ar":"استقبال وتوصيل المطار (عادي أو VIP)","en":"Airport pickup & drop-off (standard or VIP)"},
  {"id":"tour-daytrips","category":"tourism","ar":"جولات يومية داخل إسطنبول","en":"Daily tours within Istanbul"},
  {"id":"tour-multicity","category":"tourism","ar":"جولات متعددة المدن","en":"Multi-city tours"},
  {"id":"tour-packages","category":"tourism","ar":"باقات سياحية شاملة","en":"All-inclusive tour packages"},
  {"id":"tour-bosphorus","category":"tourism","ar":"رحلات بحرية (البوسفور)","en":"Bosphorus cruises"},
  {"id":"tour-driver","category":"tourism","ar":"سائق خاص بالساعة/اليوم","en":"Private driver (hourly/daily)"},
  {"id":"tour-carrental","category":"tourism","ar":"تأجير سيارات طويل المدى","en":"Long-term car rental"},
  {"id":"tour-hotels","category":"tourism","ar":"حجز الفنادق","en":"Hotel booking"},
  {"id":"tour-tickets","category":"tourism","ar":"تذاكر الأماكن والفعاليات","en":"Attraction & event tickets"},
  {"id":"tr-companion","category":"translation","ar":"مترجم مرافق (مستشفى وعلاج/دوائر/تسوّق)","en":"Companion interpreter (hospital & treatment/offices/shopping)"},
  {"id":"tr-sworn","category":"translation","ar":"ترجمة الوثائق الرسمية والمحلّفة","en":"Official & sworn document translation"},
  {"id":"tr-notary","category":"translation","ar":"تصديق النوتر والأبوستيل","en":"Notary & apostille"},
  {"id":"bank-account","category":"banking","ar":"مرافقة فتح حساب بنكي","en":"Bank account opening (escort)"},
  {"id":"ins-residence","category":"banking","ar":"التأمين الصحي للإقامة","en":"Health insurance for residence"},
  {"id":"ins-family","category":"banking","ar":"التأمين الصحي العائلي","en":"Family health insurance"},
  {"id":"ins-student","category":"banking","ar":"التأمين الصحي الطلابي العام (GSS)","en":"Student public health insurance (GSS)"},
  {"id":"ins-carhome","category":"banking","ar":"تأمين السيارات والمنزل","en":"Car & home insurance"},
  {"id":"bank-transfer","category":"banking","ar":"ربط بشركات التحويل المالي","en":"Money-transfer connections"},
  {"id":"tel-sim","category":"telecom","ar":"شريحة جوال تركية","en":"Turkish SIM card"},
  {"id":"tel-internet","category":"telecom","ar":"إنترنت منزلي","en":"Home internet"},
  {"id":"tel-utilities","category":"telecom","ar":"اشتراكات الكهرباء/الماء/الغاز (نقل وفتح)","en":"Electricity/water/gas (transfer & open)"},
  {"id":"tel-istanbulkart","category":"telecom","ar":"استخراج إسطنبول كارت","en":"Istanbulkart issuance"},
  {"id":"health-hospitals","category":"health","ar":"مستشفيات وأطباء ناطقون بالعربية وحجز المواعيد","en":"Hospitals, Arabic-speaking doctors & appointments"},
  {"id":"health-tourism","category":"health","ar":"السياحة العلاجية (زراعة شعر، أسنان، تجميل)","en":"Medical tourism (hair, dental, aesthetics)"},
  {"id":"edu-schools","category":"education","ar":"تسجيل الأطفال بالمدارس","en":"School enrollment for children"},
  {"id":"edu-denklik","category":"education","ar":"معادلة الشهادات (Denklik)","en":"Diploma equivalency (Denklik)"},
  {"id":"edu-university","category":"education","ar":"اختيار الجامعة والتسجيل الجامعي للأجانب","en":"University selection & admission for foreigners"},
  {"id":"edu-tomer","category":"education","ar":"معاهد اللغة التركية (TÖMER)","en":"Turkish language institutes (TÖMER)"},
  {"id":"edu-career","category":"education","ar":"خدمات المسار المهني للطلاب","en":"Student career services"},
  {"id":"legal-ltd","category":"business","ar":"تأسيس شركة محدودة (Limited)","en":"Limited company formation"},
  {"id":"legal-as","category":"business","ar":"تأسيس شركة مساهمة (Anonim)","en":"Joint-stock company (Anonim)"},
  {"id":"biz-location","category":"business","ar":"اختيار الموقع التجاري","en":"Commercial location scouting"},
  {"id":"biz-licenses","category":"business","ar":"رخص العمل (Ruhsat) — محلات ومطاعم وكافيهات","en":"Business licenses (Ruhsat) — shops, restaurants & cafés"},
  {"id":"biz-supply","category":"business","ar":"التوريد والمعدات","en":"Supply & equipment"},
  {"id":"biz-hiring","category":"business","ar":"التوظيف والعمالة","en":"Hiring & staffing"},
  {"id":"biz-web","category":"business","ar":"تصميم وبناء المواقع والمتاجر الإلكترونية","en":"Websites & online stores"},
  {"id":"daily-concierge","category":"daily","ar":"المرافق الشخصي (Concierge) — يرافقك ميدانياً","en":"Personal concierge — on-site with you"},
  {"id":"daily-moving","category":"daily","ar":"نقل الأثاث (Nakliyat)","en":"Furniture moving (Nakliyat)"},
  {"id":"daily-license","category":"daily","ar":"تبديل/استخراج رخصة القيادة","en":"Driving licence swap/issue"},
  {"id":"daily-emergency","category":"daily","ar":"خدمة الطوارئ والمواقف الصعبة","en":"Emergency & tough-situation help"},
  {"id":"daily-embassy","category":"daily","ar":"توجيه خدمات السفارات وتجديد الجوازات","en":"Embassy guidance & passport renewal"},
  {"id":"daily-reminders","category":"daily","ar":"تذكير ومتابعة تجديد الوثائق الدورية","en":"Document-renewal reminders & follow-up"},
  {"id":"daily-eldercare","category":"daily","ar":"رعاية وتنسيق لكبار السن والمتقاعدين","en":"Senior & retiree care coordination"},
];
