import type { LucideIcon } from 'lucide-react';
import {
  AlarmClock,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bell,
  Bookmark,
  Briefcase,
  Building2,
  Bus,
  Calculator,
  CalendarDays,
  Camera,
  Car,
  Check,
  CheckCircle2,
  Circle,
  Clock,
  Compass,
  CreditCard,
  Download,
  FileCheck,
  FileText,
  Gift,
  Globe,
  GraduationCap,
  HandHelping,
  HeartPulse,
  Home,
  Hourglass,
  IdCard,
  Inbox,
  Info,
  Landmark,
  Languages,
  Layers,
  Lightbulb,
  Lock,
  Luggage,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  Hotel,
  Navigation,
  Paperclip,
  Pencil,
  Phone,
  Plane,
  Plus,
  Receipt,
  Save,
  School,
  Scissors,
  Search,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Smile,
  Sparkles,
  Stamp,
  Star,
  Stethoscope,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  Utensils,
  X,
  XCircle,
} from 'lucide-react';

/**
 * Central name → icon registry so data-driven content (blocks, onboarding,
 * guides) can reference icons by string while staying tree-shake friendly.
 */
const ICONS = {
  'alarm-clock': AlarmClock,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  bell: Bell,
  bookmark: Bookmark,
  briefcase: Briefcase,
  building: Building2,
  bus: Bus,
  calculator: Calculator,
  calendar: CalendarDays,
  camera: Camera,
  car: Car,
  check: Check,
  'check-circle': CheckCircle2,
  circle: Circle,
  clock: Clock,
  compass: Compass,
  'credit-card': CreditCard,
  download: Download,
  'file-check': FileCheck,
  'file-text': FileText,
  gift: Gift,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'hand-helping': HandHelping,
  'heart-pulse': HeartPulse,
  home: Home,
  hourglass: Hourglass,
  'id-card': IdCard,
  inbox: Inbox,
  info: Info,
  landmark: Landmark,
  languages: Languages,
  layers: Layers,
  lightbulb: Lightbulb,
  lock: Lock,
  luggage: Luggage,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  megaphone: Megaphone,
  menu: Menu,
  'message-circle': MessageCircle,
  hotel: Hotel,
  navigation: Navigation,
  paperclip: Paperclip,
  pencil: Pencil,
  phone: Phone,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  save: Save,
  school: School,
  scissors: Scissors,
  search: Search,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  stamp: Stamp,
  star: Star,
  stethoscope: Stethoscope,
  trash: Trash2,
  'trending-up': TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  utensils: Utensils,
  x: X,
  'x-circle': XCircle,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function AppIcon({ name, className = 'w-5 h-5', fill }: { name: IconName; className?: string; fill?: string }) {
  const C = ICONS[name];
  // Default to fill="none" — lucide icons are stroke-based. Passing fill={undefined}
  // would strip lucide's own default and leave the SVG filling solid black (making
  // closed shapes like id-card / calendar render as black boxes). Callers that want
  // a filled glyph (e.g. star ratings) pass fill explicitly.
  return <C className={className} strokeWidth={1.8} fill={fill ?? 'none'} aria-hidden />;
}

/** Directional arrow that flips in RTL (via the .dir-arrow CSS rule). */
export function DirArrow({ className = 'w-4 h-4' }: { className?: string }) {
  return <ArrowRight className={`dir-arrow ${className}`} strokeWidth={2} aria-hidden />;
}
