/**
 * Regenerates src/lib/serviceIndex.generated.ts — the compact service/category
 * list the smart assistant uses to point people at a service page.
 *
 * Why a generated file: the assistant runs in a Vercel edge function, which
 * cannot afford to bundle src/data/services.ts (it pulls in ~2 MB of SEO text).
 * The list is tiny (id + two titles), so it is copied out once and committed.
 * src/lib/serviceIndex.test.ts fails whenever the catalog and this file drift,
 * so a new or renamed service cannot silently break the assistant's links.
 *
 * Run:  npm run generate:service-index
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SERVICES, SERVICE_CATEGORIES } from '../src/data/services';

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'serviceIndex.generated.ts');

const categories = SERVICE_CATEGORIES.map((c) => ({ id: c.id, ar: c.title.ar, en: c.title.en }));
const services = SERVICES.map((s) => ({ id: s.id, category: s.category, ar: s.title.ar, en: s.title.en }));

/** One object per line, so a catalog change shows up as a one-line diff. */
const asLines = (rows: object[]) => ['[', ...rows.map((r) => `  ${JSON.stringify(r)},`), ']'].join('\n');

const lines = [
  '// GENERATED by scripts/generate-service-index.ts — do not edit by hand.',
  '// Run `npm run generate:service-index` after changing src/data/services.ts.',
  '',
  'export interface IndexedCategory {',
  '  id: string;',
  '  ar: string;',
  '  en: string;',
  '}',
  '',
  'export interface IndexedService {',
  '  id: string;',
  '  category: string;',
  '  ar: string;',
  '  en: string;',
  '}',
  '',
  `export const CATEGORY_INDEX: readonly IndexedCategory[] = ${asLines(categories)};`,
  '',
  `export const SERVICE_INDEX: readonly IndexedService[] = ${asLines(services)};`,
  '',
];

writeFileSync(out, lines.join('\n'), 'utf8');
console.log(`wrote ${services.length} services in ${categories.length} categories → ${out}`);
