/**
 * Generated by scripts/resize-investment-photos.mjs — do not edit by hand.
 *
 * Maps each investment photo to the narrow variants that exist on disk beside
 * it, so <InvestmentPhoto> only ever builds a srcset out of files that were
 * really generated. A photo missing from this map is served at full size.
 *
 * `w` is the intrinsic width of the untouched source; `v` are the variant
 * widths written next to it as `<name>-<width>w.webp`.
 */
export interface InvestmentPhotoVariants {
  /** Intrinsic width of the original file. */
  w: number;
  /** Generated variant widths, ascending. */
  v: number[];
}

export const INVESTMENT_PHOTO_VARIANTS: Record<string, Record<string, InvestmentPhotoVariants>> = {
  "address-residence-istanbul": {
    "1.webp": {
      "w": 575,
      "v": [
        400
      ]
    },
    "2.webp": {
      "w": 780,
      "v": [
        400
      ]
    },
    "3.webp": {
      "w": 1024,
      "v": [
        400,
        800
      ]
    }
  },
  "allure-tower-avcilar": {
    "1.webp": {
      "w": 412,
      "v": [
        400
      ]
    },
    "2.webp": {
      "w": 750,
      "v": [
        400
      ]
    },
    "3.webp": {
      "w": 568,
      "v": [
        400
      ]
    }
  },
  "babacan-lagoon-gaziosmanpasa": {
    "1.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    },
    "2.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    },
    "3.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    }
  },
  "basak-port": {
    "1.webp": {
      "w": 3000,
      "v": [
        400,
        800
      ]
    },
    "2.webp": {
      "w": 3000,
      "v": [
        400,
        800
      ]
    }
  },
  "casablu-vadi-beylikduzu": {
    "1.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    },
    "2.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    }
  },
  "emaar-square-residences": {
    "1.webp": {
      "w": 1620,
      "v": [
        400,
        800
      ]
    }
  },
  "focus-gunesli-bagcilar": {
    "1.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    },
    "2.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    }
  },
  "lotus-sisli": {
    "1.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    },
    "2.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    }
  },
  "rams-park-house-maslak": {
    "1.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    },
    "2.webp": {
      "w": 1920,
      "v": [
        400,
        800
      ]
    }
  },
  "residence-inn-deluxia": {
    "1.webp": {
      "w": 1985,
      "v": [
        400,
        800
      ]
    },
    "2.webp": {
      "w": 1985,
      "v": [
        400,
        800
      ]
    }
  },
  "seba-central-kagithane": {
    "1.webp": {
      "w": 2560,
      "v": [
        400,
        800
      ]
    },
    "2.webp": {
      "w": 2560,
      "v": [
        400,
        800
      ]
    },
    "3.webp": {
      "w": 2227,
      "v": [
        400,
        800
      ]
    }
  }
};
